task_id: airbnb004
status: ready
description: Add a primary key to a dbt model.
notes: |-
  - This needs to figure out a way to check if the primary key is derived and not just a row_count or something.
prompts:
  - key: base
    prompt: |-
      Add review_id as a primary key to the fct_reviews table and update the model.
author_name: test
author_email: test
difficulty: medium
tags:
  - data-inspection
  - dbt
  - model-refactor

# Variants for different database and project combinations
variants:
- db_type: duckdb
  db_name: airbnb
  project_type: dbt
  project_name: airbnb

- db_type: snowflake
  db_name: airbnb
  project_type: dbt
  project_name: airbnb
  migration_directory: airbnb__duckdb_to_snowflake

- db_type: snowflake
  db_name: airbnb
  project_type: dbt-fusion
  project_name: airbnb
  migration_directory: airbnb__duckdb_to_snowflake_dbtf